--CREATE TEMPORARY TABLESPACE AdminVentasTMP TEMPFILE 'C:\Oracle\oradata\GOKU\AdminVentasTMP.dbf' SIZE 150M autoextend on next 50M MAXSIZE 1G;
--CREATE TABLESPACE AdminVentas DATAFILE 'C:\Oracle\oradata\GOKU\DTFARSA_CABLEVISION16.dbf' SIZE 150M autoextend on next 50M MAXSIZE 1G;
--CREATE USER AdminVentas IDENTIFIED BY Admin123 DEFAULT TABLESPACE AdminVentas TEMPORARY TABLESPACE AdminVentasTMP;
--GRANT DBA TO AdminVentas;

CREATE TABLE ESTADOS_COBROS(
CBR_ESTADO_ID SMALLINT PRIMARY KEY,
CBR_ESTADO_FACTURA CHAR(20) NOT NULL,
CONSTRAINT CH_ESTADOS CHECK(CBR_ESTADO_ID BETWEEN 1 AND 5)
);

--TRUNCATE TABLE VNT_CAT_REGIONES;
--ALTER TABLE VNT_CAT_REGIONES MODIFY(VNT_CVE_REGION GENERATED AS IDENTITY (START WITH 1));

CREATE TABLE VNT_CAT_REGIONES(  ---SE AGREGA TABLA PARA QUE LA INFORMACIÓN ESTE MÁS COMPLETA Y LA LLAVE DE REGION SEA UNA CLAVE FORANEA Y NO UN SIMPLE NUMERO
VNT_CVE_REGION SMALLINT GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),  --CON ESTA PROPIEDAD EL CAMPO SERÁ AUTOINCREMENTABLE
VNT_NOM_REGION VARCHAR(50) NOT NULL,
CONSTRAINT PK_CR PRIMARY KEY (VNT_CVE_REGION),
CONSTRAINT CH_CVEREG CHECK(VNT_CVE_REGION BETWEEN 1 AND 9) ---CON ESTA VALIDACIÓN SE VALIDA QUE EL VALOR DE LONGITUD DEFINIDO "2" SE RESPETE
);

CREATE TABLE CTL_CLIENTES
(
CTL_CVE_CLIENTE SMALLINT,
CTL_NOM_CLIENTE VARCHAR(60) NOT NULL,
CTL_DIRECCIONES VARCHAR(120) NOT NULL,
CTL_TELEFONO CHAR(12) NOT NULL,
CTL_CORREO VARCHAR(60),
CONSTRAINT PK_CVEC PRIMARY KEY(CTL_CVE_CLIENTE),
--CONSTRAINT CH_TEL CHECK (CTL_TELEFONO LIKE '[0-9][0-9] [0-9][0-9][0-9][0-9] [0-9][0-9][0-9][0-9]'),
CONSTRAINT CH_CORREO CHECK(CTL_CORREO LIKE '%@%')
);
ALTER TABLE CTL_CLIENTES DROP CONSTRAINT CH_TEL;
COMMIT;
--DROP TABLE VNT_CAT_CIUDADES
CREATE TABLE VNT_CAT_CIUDADES(
VNT_CVE_CIUDAD SMALLINT ,
VNT_CVE_REGION SMALLINT,
VNT_NOMBRE_CIUDAD VARCHAR(50) NOT NULL,
CONSTRAINT PK_VNTCITY  PRIMARY KEY(VNT_CVE_CIUDAD),
CONSTRAINT FK_CVEREG FOREIGN KEY (VNT_CVE_REGION) REFERENCES VNT_CAT_REGIONES (VNT_CVE_REGION) ON DELETE SET NULL,
CONSTRAINT CH_CVECIT CHECK(VNT_CVE_CIUDAD BETWEEN 1 AND 9) ---CON ESTA VALIDACIÓN SE VALIDA QUE EL VALOR DE LONGITUD DEFINIDO "2" SE RESPETE
);
--DROP TABLE VNT_FACTURACIONES
CREATE TABLE VNT_FACTURACIONES
(
VNT_ID_FACTURA NUMBER(9,0), --EN ORACLE NO EXISTE EL TIPO DE DATO INT, EN SU LUGAR ES EL TIPO DE DATO NUMBER
                            --DONDE SE LE ESPECIFICA EL NUMERO DE ENTEROS QUE PUEDE RECIBIR 
                            --Y EL NÚMERO DE DECIMALES QUE PUEDE RECIBIR(EN ESTE CASO ES 0)
CTL_CVE_FKCLIENTE SMALLINT,
VNT_CVE_FKCIUDAD SMALLINT,
CBR_ESTADO_FACTURA SMALLINT,
VNT_MONTO_FACTURA DECIMAL(14,2)NOT NULL,
VNT_IVA_FACTURA DECIMAL(14,2) NOT NULL,
VNT_FECHA_FACTURA DATE NOT NULL, ---EN ORACLE EL TIPO DE DATO DATE GUARDA FECHA Y HORA 
CONSTRAINT PK_IDF PRIMARY KEY(VNT_ID_FACTURA),
CONSTRAINT FK_CL FOREIGN KEY(CTL_CVE_FKCLIENTE) REFERENCES CTL_CLIENTES (CTL_CVE_CLIENTE) ON DELETE SET NULL, ---SI SE ELIMINA EL CLIENTE ESTE VALOR SE PONE EN "NULL" PERO NO SE ELIMINA EL REGISTRO
CONSTRAINT FK_CITY FOREIGN KEY(VNT_CVE_FKCIUDAD) REFERENCES VNT_CAT_CIUDADES (VNT_CVE_CIUDAD) ON DELETE SET NULL,
CONSTRAINT FK_CBRFAC FOREIGN KEY(CBR_ESTADO_FACTURA) REFERENCES ESTADOS_COBROS (CBR_ESTADO_ID) ON DELETE SET NULL,
CONSTRAINT CH_MONTO CHECK(VNT_MONTO_FACTURA>0.0)
);
--DROP TABLE BACKUP_VNT_FACTURACIONES
CREATE TABLE BACKUP_VNT_FACTURACIONES ---AL SER UNA TABLA DE RESPALDO NO LE DEFINI CONSTRAINTS, SOLO EL DE LA PRIMARY KEY
(
ID_REGISTRO INT GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
FECHA_RESPALDO DATE DEFAULT SYSDATE,
VNT_ID_FACTURA NUMBER(9,0),
CTL_CVE_FKCLIENTE SMALLINT,
VNT_CVE_FKCIUDAD SMALLINT,
CBR_ESTADO_FACTURA SMALLINT,
VNT_MONTO_FACTURA DECIMAL(14,2),
VNT_IVA_FACTURA DECIMAL(14,2),
VNT_FECHA_FACTURA DATE,
CONSTRAINT PK_nIDF PRIMARY KEY(ID_REGISTRO)
);

--CREACION DE INDICES
CREATE INDEX CTL_CLIENTES_INDEX1 ON CTL_CLIENTES (CTL_CVE_CLIENTE)
CREATE INDEX VNT_CAT_CIUDADES_INDEX1 ON VNT_CAT_CIUDADES (VNT_CVE_CIUDAD ASC)
--------------------------------------------------------------------------------------
/*
CREATE OR REPLACE TRIGGER TG_BAKUP_FACTURAS
AFTER INSERT
ON VNT_FACTURACIONES FOR EACH ROW
BEGIN
MERGE INTO BACKUP_VNT_FACTURACIONES T2 USING VNT_FACTURACIONES T1
	ON (T2.VNT_ID_FACTURA=T1.VNT_ID_FACTURA)
	WHEN NOT MATCHED THEN
	INSERT
	(
		VNT_ID_FACTURA ,
		CTL_CVE_FKCLIENTE ,
		VNT_CVE_FKCIUDAD ,
		CBR_ESTADO_FACTURA ,
		VNT_MONTO_FACTURA ,
		VNT_IVA_FACTURA ,
		VNT_FECHA_FACTURA 
	)
	VALUES
	(
		T1.VNT_ID_FACTURA ,
		T1.CTL_CVE_FKCLIENTE ,
		T1.VNT_CVE_FKCIUDAD ,
		T1.CBR_ESTADO_FACTURA ,
		T1.VNT_MONTO_FACTURA ,
		T1.VNT_IVA_FACTURA ,
		T1.VNT_FECHA_FACTURA 
	);
END;
*/
---------------------------------------------
/*SON DATOS DE PRUEBA, NO SE DEFINIO PREVIAMENTE LOS DATOS REALES*/
INSERT INTO ESTADOS_COBROS(CBR_ESTADO_ID, CBR_ESTADO_FACTURA)VALUES(1,'PENDIENTE');
INSERT INTO ESTADOS_COBROS(CBR_ESTADO_ID, CBR_ESTADO_FACTURA)VALUES(2,'PAGADO');
INSERT INTO ESTADOS_COBROS(CBR_ESTADO_ID, CBR_ESTADO_FACTURA)VALUES(3,'FACTURADO');
INSERT INTO ESTADOS_COBROS(CBR_ESTADO_ID, CBR_ESTADO_FACTURA)VALUES(4,'CANCELADO');
INSERT INTO ESTADOS_COBROS(CBR_ESTADO_ID, CBR_ESTADO_FACTURA)VALUES(5,'URGENTE');
COMMIT;
SELECT * FROM ESTADOS_COBROS;
INSERT INTO VNT_CAT_REGIONES(VNT_NOM_REGION)VALUES('NORTE');
INSERT INTO VNT_CAT_REGIONES(VNT_NOM_REGION)VALUES('SUR');
INSERT INTO VNT_CAT_REGIONES(VNT_NOM_REGION)VALUES('ESTE');
INSERT INTO VNT_CAT_REGIONES(VNT_NOM_REGION)VALUES('OESTE');
COMMIT;
---SON LOS DATOS PROPORCIONADOS
INSERT INTO CTL_CLIENTES (CTL_CVE_CLIENTE, CTL_NOM_CLIENTE, CTL_DIRECCIONES, CTL_TELEFONO, CTL_CORREO) VALUES (1020, 'Fancisco Perez', 'calle 25 - 12, Col. Estado de Mexico', '55 4952 1234', 'fperes@gmail.com');
INSERT INTO CTL_CLIENTES (CTL_CVE_CLIENTE, CTL_NOM_CLIENTE, CTL_DIRECCIONES, CTL_TELEFONO, CTL_CORREO) VALUES (1021, 'Alicia Torres', 'calle alameda - 122, Col. San Pedro', '56 4952 1234', 'atorres@gmail.com');
INSERT INTO CTL_CLIENTES (CTL_CVE_CLIENTE, CTL_NOM_CLIENTE, CTL_DIRECCIONES, CTL_TELEFONO, CTL_CORREO) VALUES (1022, 'Soledad James', 'calle Allende - 12, Col. San Fernando', '57 4952 1234', 'sjaimes@gmail.com');
INSERT INTO CTL_CLIENTES (CTL_CVE_CLIENTE, CTL_NOM_CLIENTE, CTL_DIRECCIONES, CTL_TELEFONO, CTL_CORREO) VALUES (1023, 'Gerardo Hernandez', 'calle hidalgo - 32, Col. Xochimilco', '58 4952 1234', 'ghernandez@gmail.com');
INSERT INTO CTL_CLIENTES (CTL_CVE_CLIENTE, CTL_NOM_CLIENTE, CTL_DIRECCIONES, CTL_TELEFONO, CTL_CORREO) VALUES (1024, 'Araceli Mendoza', 'calle Juarez - 432, Col. Ejercito', '59 4952 1234', 'amendoza@hotmail.com');
INSERT INTO CTL_CLIENTES (CTL_CVE_CLIENTE, CTL_NOM_CLIENTE, CTL_DIRECCIONES, CTL_TELEFONO, CTL_CORREO) VALUES (1025, 'Lizeth Zarate', 'calle Pitagoras - 142, Col. Vista Alegre', '60 4952 1234', 'lzarate@hotmail.com');
INSERT INTO CTL_CLIENTES (CTL_CVE_CLIENTE, CTL_NOM_CLIENTE, CTL_DIRECCIONES, CTL_TELEFONO, CTL_CORREO) VALUES (1026, 'Rosa Pereyra', 'calle La Fragua - 1232, Col. Ejidos', '61 4952 1234', 'rpereyra@gmail.com');
INSERT INTO CTL_CLIENTES (CTL_CVE_CLIENTE, CTL_NOM_CLIENTE, CTL_DIRECCIONES, CTL_TELEFONO, CTL_CORREO) VALUES (1027, 'Guadaluoe Hernandez', 'calle Venustiano carranza - 1322, Col. Hipodromo', '62 4952 1234', 'ghernandez@hotmail.com');
INSERT INTO CTL_CLIENTES (CTL_CVE_CLIENTE, CTL_NOM_CLIENTE, CTL_DIRECCIONES, CTL_TELEFONO, CTL_CORREO) VALUES (1028, 'Joaquin Beltra', 'calle  16 de septiembre - 234, Col. El Reloj', '63 4952 1234', 'jbeltran@gmail.com');
INSERT INTO CTL_CLIENTES (CTL_CVE_CLIENTE, CTL_NOM_CLIENTE, CTL_DIRECCIONES, CTL_TELEFONO, CTL_CORREO) VALUES (1029, 'Rosario Alcantara', 'calle 5 de mayo - 12321, Col. Aztecas', '64 4952 1234', 'ralcantara@gmail.com');
INSERT INTO CTL_CLIENTES (CTL_CVE_CLIENTE, CTL_NOM_CLIENTE, CTL_DIRECCIONES, CTL_TELEFONO, CTL_CORREO) VALUES (1030, 'Cristina Melendez', 'calle 5 de febrero - 1262, Col. L Herradura', '65 4952 1234', 'cmelendez@hotmail.com');
INSERT INTO CTL_CLIENTES (CTL_CVE_CLIENTE, CTL_NOM_CLIENTE, CTL_DIRECCIONES, CTL_TELEFONO, CTL_CORREO) VALUES (1031, 'Cesar Agular', 'calle Palma - 1298, Col. Centro', '66 4952 1234', 'caguilar@hotmail.com');
INSERT INTO CTL_CLIENTES (CTL_CVE_CLIENTE, CTL_NOM_CLIENTE, CTL_DIRECCIONES, CTL_TELEFONO, CTL_CORREO) VALUES (1032, 'Mariana Juarez', 'calle San Juan - 1287, Col. Prados', '67 4952 1234', 'mjuarez@hotmail.com');
COMMIT;

INSERT INTO VNT_CAT_CIUDADES (VNT_CVE_CIUDAD, VNT_CVE_REGION, VNT_NOMBRE_CIUDAD) VALUES (1, 1, 'CDMX');
INSERT INTO VNT_CAT_CIUDADES (VNT_CVE_CIUDAD, VNT_CVE_REGION, VNT_NOMBRE_CIUDAD) VALUES (2, 1, 'Estado de México');
INSERT INTO VNT_CAT_CIUDADES (VNT_CVE_CIUDAD, VNT_CVE_REGION, VNT_NOMBRE_CIUDAD) VALUES (3, 2, 'Puebla');
INSERT INTO VNT_CAT_CIUDADES (VNT_CVE_CIUDAD, VNT_CVE_REGION, VNT_NOMBRE_CIUDAD) VALUES (4, 2, 'Veracruz');
INSERT INTO VNT_CAT_CIUDADES (VNT_CVE_CIUDAD, VNT_CVE_REGION, VNT_NOMBRE_CIUDAD) VALUES (5, 3, 'Querétaro');
INSERT INTO VNT_CAT_CIUDADES (VNT_CVE_CIUDAD, VNT_CVE_REGION, VNT_NOMBRE_CIUDAD) VALUES (6, 3, 'Celaya');
INSERT INTO VNT_CAT_CIUDADES (VNT_CVE_CIUDAD, VNT_CVE_REGION, VNT_NOMBRE_CIUDAD) VALUES (7, 4, 'Nuevo Leó');
INSERT INTO VNT_CAT_CIUDADES (VNT_CVE_CIUDAD, VNT_CVE_REGION, VNT_NOMBRE_CIUDAD) VALUES (8, 4, 'Coahuila');
INSERT INTO VNT_CAT_CIUDADES (VNT_CVE_CIUDAD, VNT_CVE_REGION, VNT_NOMBRE_CIUDAD) VALUES (9, 4, 'Tamaulipas');
COMMIT;
